component: "geonames/0030_drop"
input_subdir_city: "city"
output_subdir_city: "city"
keep_columns:
  - "city_id"
  - "city_name"
  - "city_name_ascii"
  - "city_name_alt"
  - "feature_class"
  - "feature_code"
  - "country_code"
  - "admin1_code"
  - "admin2_code"
  - "admin3_code"
  - "admin4_code"
  - "population"
  - "timezone"
  - "modified_at"
  - "coord_raw"
compression: "zstd"
compression_level: 22
